### ISSUE TITLE
Curious about your challenge page.

### ISSUE THREAD

**Issue by orenwf** [truveris/truveris.github.io#11]
I tried the challenge you guys have on this web page. If you have a moment I'd like to discuss why my hash didn't come out correctly, according to your recruiter. I am fairly certain that my bash commands were the right ones, and I had an accurate reading of the instructions. Feel free to e-mail me if you don't want to discuss here.

**Comment by tamentis** [comment]
You were very close, but it was indeed wrong :)

**Comment by orenwf** [comment]
yes, the additional newlines messed it up for me.
